#Page Rank
## Peringkat Halaman (PageRank): Membongkar Rahasia di Balik Peringkat Website

**Peringkat Halaman**, atau PageRank, adalah sebuah algoritma canggih yang diciptakan oleh Larry Page dan Sergey Brin, untuk menentukan **kualitas dan relevansi** sebuah halaman web. Algoritma ini memainkan peran penting dalam **menentukan peringkat** halaman web di hasil pencarian Google.

**Faktor-faktor yang Mempengaruhi PageRank:**

* **Jumlah Tautan:** Semakin banyak tautan yang mengarah ke halaman web, semakin tinggi PageRank-nya.
* **Kualitas Tautan:** Tautan dari situs web yang memiliki PageRank tinggi lebih bernilai daripada tautan dari situs web baru atau berkualitas rendah.
* **Posisi Tautan:** Tautan yang ditempatkan di bagian utama halaman web (seperti body content) lebih bernilai daripada tautan di footer atau sidebar.
* **Teks Tautan:** Teks tautan yang deskriptif dan relevan dengan konten halaman web lebih bernilai daripada teks tautan generik.






### Mari kita nyatakan dengan \( A \) matriks transisi dari grafik, \( A = \begin{pmatrix} 0 & 0 & 1 & \frac{1}{2} \\ 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & \frac{1}{2} \\ 0 & 1 & 1 & 0 \end{pmatrix} \).

### Sudut pandang sistem dinamis:

Misalkan pada awalnya tingkat kepentingannya didistribusikan secara merata di antara 4 node, masing-masing mendapatkan \begin{pmatrix} \frac{1}{4} \end{pmatrix}. Dilambangkan dengan \( v \) vektor peringkat awal, yang semua entrinya sama dengan \begin{pmatrix}\frac{1}{4}\end{pmatrix}. Setiap tautan masuk meningkatkan pentingnya laman web, jadi pada langkah 1, kami memperbarui peringkat setiap laman dengan menambahkan nilai saat ini pada pentingnya tautan masuk. Ini sama dengan mengalikan matriks \( A \) dengan \( v \). Pada langkah 1, vektor kepentingan baru adalah \( v_1 = Av \). Kita dapat mengulangi prosesnya, sehingga pada langkah 2, vektor kepentingan yang diperbarui adalah \( v_2 = A(Av) = A^2 v \). Perhitungan numerik memberikan:

\[
v = \begin{pmatrix} 0.25 \\ 0.25 \\ 0.25 \\ 0.25 \end{pmatrix} Av = \begin{pmatrix} 0.37 \\ 0.08 \\ 0.33 \\ 0.20 \end{pmatrix} A^2 v = \begin{pmatrix} 0.37 \\ 0.08 \\ 0.33 \\ 0.20 \end{pmatrix}
\]

\[
A^3 v = \begin{pmatrix} 0.35 \\ 0.14 \\ 0.32 \\ 0.19 \end{pmatrix} A^4 v = \begin{pmatrix} 0.39 \\ 0.11 \\ 0.31 \\ 0.19 \end{pmatrix} A^5 v = \begin{pmatrix} 0.39 \\ 0.12 \\ 0.29 \\ 0.19 \end{pmatrix}
\]

\[
A^6 v = \begin{pmatrix} 0.38 \\ 0.12 \\ 0.29 \\ 0.19 \end{pmatrix} A^7 v = \begin{pmatrix} 0.38 \\ 0.12 \\ 0.29 \\ 0.19 \end{pmatrix} A^8 v = \begin{pmatrix} 0.38 & 0.12 & 0.29 & 0.19 \end{pmatrix}
\]

Kita perhatikan bahwa barisan iterasi v , Av , ..., A^k v cenderung ke nilai kesetimbangan \( v^* = \begin{pmatrix} 0.38 \\ 0.12 \\ 0.29 \\ 0.19 \end{pmatrix} \).

### Sudut pandang aljabar linier:

Mari kita nyatakan dengan \( x_1, x_2, x_3, dan x_4 \) pentingnya keempat halaman tersebut. Menganalisis situasi di setiap node, kita mendapatkan sistem:

\[
\begin{cases}
x_1 = 1 \cdot x_3 + \frac{1}{2} \cdot x_4 \\
x_2 = \frac{1}{3} \cdot x_1 \\
x_3 = \frac{1}{3} \cdot x_1 + \frac{1}{2} \cdot x_4 \\
x_4 = \frac{1}{3} \cdot x_1 + 1 \cdot x_2 + \frac{1}{2} \cdot x_4
\end{cases}
\]

Hal ini setara dengan menanyakan solusi persamaan ( A dot \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} \). Dari Contoh tersebut kita mengetahui bahwa vektor eigen yang bersesuaian dengan nilai eigen 1 berbentuk \( c cdot \begin{pmatrix} 12 \\ 4 \\ 9 \\ 6 \end{pmatrix} \). Karena PageRank seharusnya hanya mencerminkan kepentingan relatif dari node, dan karena vektor eigen hanyalah kelipatan skalar satu sama lain, kita dapat memilih salah satu dari mereka untuk menjadi vektor pagerank kita. pilih v sebagai vektor eigen unik dengan jumlah semua entri sama dengan 1. (Terkadang kita menyebutnya sebagai vektor eigen probabilistik yang sesuai dengan nilai eigen 1). Vektor eigen \begin{pmatrix}\frac{1}{31} \end{pmatrix}.


 \begin{pmatrix} 12 \\ 4 \\ 9 \\ 6 \end{pmatrix} ~ \begin{pmatrix} 0.38 \\ 0.12 \\ 0.29 \\ 0.19 \end{pmatrix} \
 adalah vektor PageRank kita.



### Sudut pandang probabilistik:

Karena pentingnya suatu halaman web diukur dengan popularitasnya (berapa banyak link masuk yang dimilikinya), kita dapat melihat pentingnya halaman \( i \) sebagai probabilitas bahwa seorang peselancar acak di Internet yang membuka browser ke halaman mana pun dan mulai mengikuti hyperlink, mengunjungi halaman \( i \). Kita dapat menafsirkan bobot yang kita tetapkan pada tepi grafik dengan cara yang probabilistik: Seorang peselancar acak yang sedang melihat halaman web 2, memiliki ½ probabilitas untuk membuka halaman 3, dan ½ probabilitas untuk membuka halaman 4. Kita dapat memodelkan prosesnya sebagai jalan acak pada grafik. Setiap halaman mempunyai probabilitas yang sama \begin{pmatrix}\frac{1}{4} \end{pmatrix} untuk dipilih sebagai titik awal. Jadi, distribusi probabilitas awal diberikan oleh vektor kolom \(\begin{pmatrix} \frac{1}{4} \\ \frac{1}{4} \\ \frac{1}{4} \\ \frac{1}{4} \end{pmatrix}\). Peluang halaman \( i \) dikunjungi setelah satu langkah sama dengan \( A \cdot x \), dan seterusnya. Peluang halaman \( i \) dikunjungi setelah \( k \) langkah sama dengan \( A^k \cdot x \). Barisan \( Ax, A^2 x, A^3 x, ..., A^k x, ... \) dalam hal ini konvergen menjadi vektor probabilistik unik \( v^* \). Dalam konteks ini \( v^* \) disebut distribusi stasioner dan akan menjadi vektor PageRank kita. Selain itu, entri ke-\(i\) dalam vektor \( v^* \) hanyalah probabilitas bahwa pada setiap saat seorang peselancar acak mengunjungi halaman \( i \). Perhitungannya identik dengan yang kami lakukan dalam interpretasi sistem dinamik, hanya makna yang kami berikan pada setiap langkah yang sedikit berbeda.

#CONTOH PENYELESAIAN SOAL YANG ADA DI KELAS

Untuk menghitung \( V2 \), kita harus melakukan perkalian matriks antara matriks \( A \) dan vektor \( V \). Hasil dari perkalian ini kemudian akan dibulatkan ke angka terdekat.

$$
\begin{align*}
\text{Matriks(A)} &= \begin{bmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{bmatrix}
\end{align*}
$$


$$
\begin{align*}
\text{Vektor(V):} &=
\begin{bmatrix}
0.25 \\
0.25 \\
0.25 \\
0.25
\end{bmatrix}
\end{align*}
$$

$$
\begin{align*}
\text{perkalian \( V2 = A  V \):}
\end{align*}
$$

$$
\begin{align*}
\text{V2} &=
\begin{bmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{bmatrix}
\begin{bmatrix}
\times
\end{bmatrix}
\begin{bmatrix}
0.25 \\
0.25 \\
0.25 \\
0.25
\end{bmatrix}
\end{align*}
$$

hasil yang di dapat:

$$
\begin{align*}
\begin{bmatrix}
V2[0] = 0 \cdot 0.25 + 0 \cdot 0.25 + 1 \cdot 0.25 + \frac{1}{2} \cdot 0.25 = 0 + 0 + 0.25 + 0.125 = 0.375
\end{bmatrix}
\end{align*}
$$

$$
\begin{align*}
\begin{bmatrix}
V2[1] = \frac{1}{3} \cdot 0.25 + 0 \cdot 0.25 + 0 \cdot 0.25 + 0 \cdot 0.25 = 0.0833
\end{bmatrix}
\end{align*}
$$

$$
\begin{align*}
\begin{bmatrix}
V2[2] = \frac{1}{3} \cdot 0.25 + \frac{1}{2} \cdot 0.25 + 0 \cdot 0.25 + \frac{1}{2} \cdot 0.25 = 0.0833 + 0.125 + 0 + 0.125 = 0.3333
\end{bmatrix}
\end{align*}
$$

$$
\begin{align*}
\begin{bmatrix}
V2[3] = \frac{1}{3} \cdot 0.25 + \frac{1}{2} \cdot 0.25 + 0 \cdot 0.25 + 0 \cdot 0.25 = 0.0833 + 0.125 = 0.2083
\end{bmatrix}
\end{align*}
$$

Hasil yang sudah dibulatkan :
$$
\begin{align*}
\text{V2}&=
\begin{bmatrix}
0.38 \\
0.08 \\
0.33 \\
0.21
\end{bmatrix}
\end{align*}
$$

hasil akhir :
$$
\begin{align*}
\begin{bmatrix}
0.38 \\
0.08 \\
0.33 \\
0.21
\end{bmatrix}
\end{align*}
$$

In [1]:
import numpy as np

# Definisikan matriks A dan vektor V sebagai array NumPy
A = np.array([
    [0, 0, 1, 1/2],
    [1/3, 0, 0, 0],
    [1/3, 1/2, 0, 1/2],
    [1/3, 1/2, 0, 0]
])

V = np.array([
    [0.25],
    [0.25],
    [0.25],
    [0.25]
])

# Lakukan perkalian matriks A dengan vektor V
V2 = np.dot(A, V)

# Bulatkan hasil ke dua angka desimal
V2_rounded = np.round(V2, 2)

print("V2:", V2_rounded)


V2: [[0.38]
 [0.08]
 [0.33]
 [0.21]]


In [2]:
print("V0:")
print(V)

# Iterasi hingga V15
for i in range(1, 16):
    V = np.dot(A, V)
    print(f"V{i}:")
    print(V,"\n")


V0:
[[0.25]
 [0.25]
 [0.25]
 [0.25]]
V1:
[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]] 

V2:
[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]] 

V3:
[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]] 

V4:
[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]] 

V5:
[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]] 

V6:
[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]] 

V7:
[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]] 

V8:
[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]] 

V9:
[[0.38657407]
 [0.12890625]
 [0.29065394]
 [0.19386574]] 

V10:
[[0.38758681]
 [0.12885802]
 [0.29024402]
 [0.19331115]] 

V11:
[[0.38689959]
 [0.1291956 ]
 [0.29028019]
 [0.19362461]] 

V12:
[[0.3870925 ]
 [0.12896653]
 [0.29037664]
 [0.19356433]] 

V13:
[[0.38715881]
 [0.12903083]
 [0.29029626]
 [0.1935141 ]] 

V14:
[[0.38705331]
 [0.12905294]
 [0.2903254 ]
 [0.19356835]] 

V15:
[[0.38710958]
 [0.12901777]
 [0.29032841]
 [0.19354424]] 

