# Matriks Determinan
determinan merupakan sebuah nilai yang dapat dihitung dari suatu elemen matriks persegi

# sifat sifat determinant
cari fungsi matrix determinant
Sifat – Sifat Determinan Matriks
Ada beberapa sifat – sifat determinan matriks, yaitu diantarannya:
1. Apabila semua elemen dari salah satu baris atau kolom sama dengan nol, maka determinan matriks tersebut adalah nol. Perhatikan contoh berikut:
Misalkan  : This is the rendered form of the equation. You can not edit this directly. Right click will give you the option to save the image, and in most browsers you can drag the image onto your desktop or another program.
2. Apabila semua elemen dari salah satu baris atau kolom itu sama dengan elemen-elemen baris atau kolom lain, maka determinan matriks tersebut adalah nol.
Perhatikan contoh berikut:
Misalkan: B = This is the rendered form of the equation. You can not edit this directly. Right click will give you the option to save the image, and in most browsers you can drag the image onto your desktop or another program. (Sebab elemen-elemen baris ke-1 dan ke-3 adalah sama).
3. Apabila elemen-elemen salah satu dari baris atau kolom adalah merupakan kelipatan dari elemen-elemen baris atau kolom lain maka determinan matriks tersebut adalah nol.
Perhatikan contoh di bawahberikut:
Misalkan: A = This is the rendered form of the equation. You can not edit this directly. Right click will give you the option to save the image, and in most browsers you can drag the image onto your desktop or another program. (Sebab elemen-elemen baris ke-3 sama dengan kelipatan elemen-elemen baris ke-1).
4. |AB| : |A| ×|B|
5. |AT| = |A|, untuk AT ialah transpose dari matriks A.
6. |A–1| = This is the rendered form of the equation. You can not edit this directly. Right click will give you the option to save the image, and in most browsers you can drag the image onto your desktop or another program. , untuk A–1 ialah invers dari matriks A.
7. |kA| = kn |A|, untuk A ordo n × n dan k adalahsuatu konstanta.


#Membuktikan bahwa determinan dari matriks identitas adalah 1

In [1]:
import numpy as np

def matrix_determinant(matrix):
    return np.linalg.det(matrix)

# Membuat matriks identitas 3x3
identity_matrix = np.identity(3)

# Menghitung determinan matriks identitas
det = matrix_determinant(identity_matrix)

print("Matriks Identitas:")
print(identity_matrix)
print("Determinannya adalah:", det)


Matriks Identitas:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinannya adalah: 1.0


#Merubah baris akan merubah tanda dan hasil dari determinan

In [2]:
import numpy as np

def matrix_determinant(matrix):
    return np.linalg.det(matrix)

# Membuat matriks 3x3 untuk demonstrasi
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriks awal:")
print(matrix)

# Menghitung determinan matriks awal
det_original = matrix_determinant(matrix)
print("Determinan matriks awal:", det_original)

# Mengubah baris pertama dengan baris kedua
matrix[0], matrix[1] = matrix[1], matrix[0]

print("\nMatriks setelah mengubah baris pertama dengan baris kedua:")
print(matrix)

# Menghitung determinan matriks setelah perubahan baris
det_changed = matrix_determinant(matrix)
print("Determinan matriks setelah perubahan baris:", det_changed)

# Perubahan determinan
det_change = det_changed - det_original
print("Perubahan determinan:", det_change)


Matriks awal:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinan matriks awal: 0.0

Matriks setelah mengubah baris pertama dengan baris kedua:
[[4 5 6]
 [4 5 6]
 [7 8 9]]
Determinan matriks setelah perubahan baris: 0.0
Perubahan determinan: 0.0


#jika sebuah baris merupakan kelipatan dari baris yang lain maka matrix akan memiliki determinan 0

In [3]:
import numpy as np
matrix = np.array([[1, 2, 1], [2, 4, 2], [2, 1, 2]])
matrix1 = np.array([[2, 4, 2], [1, 2, 1], [2, 1, 2]])
e = round(np.linalg.det(matrix)) #bilbul
determinant1 = round(np.linalg.det(matrix1))
print('baris 2 perkalian baris 1 : ',e)
print('baris 2 di tukar dengan baris 1 : ',determinant1)

baris 2 perkalian baris 1 :  0
baris 2 di tukar dengan baris 1 :  0


In [4]:
import numpy as np
matrix = np.array([[1, 2, 1], [2, 4, 2], [2, 4, 3]])
f = round(np.linalg.det(matrix)) #bilbul
print(f)

0


In [5]:
import numpy as np
matrix = np.array([[6, 2, 4], [2, 4, 2], [4, 2, 4]])
g = round(np.linalg.det(matrix)) #bilbul
print(g)

24


In [6]:
import numpy as np
matrix = np.array([[3, 4], [2, 1]])
matrix1 = np.array([[6, 8], [4, 2]])
A = round(np.linalg.det(matrix))
h = round(np.linalg.det(matrix1))
print(A)
print(h)

-5
-20


In [10]:
import numpy as np
matrixA = np.array([[3, 4], [2, 1]])
matrixI = np.array([[6,8], [2, 1] ])
A = round(np.linalg.det(matrixA)) #bilbul
I = round(np.linalg.det(matrixI))
print(A)
print(I)

-5
-10


In [13]:
import numpy as np
segitigaatas = np.array([[3, 4, 6], [0, 1, 3], [0,0,7]])
segitigabawah = np.array([[6,0,0], [9, 7, 0],[2, 1, 4] ])
Det1 = round(np.linalg.det(segitigaatas)) #bilbul
Det2 = round(np.linalg.det(segitigabawah))
print(Det1)
print(Det2)

21
168


In [14]:
import numpy as np
matrix = np.array([[2, 1,], [1, 1]])
matrix1 = np.array([[1, 1], [1, 1]])
A = round(np.linalg.det(matrix))
B = round(np.linalg.det(matrix1))
print(A)
print(B)

1
0
