##penyelesaian sistem persamaan linier tentang matrix invers
###sifat sifat matriks invers
###mencari invers dengan eliminasi gauss jordan
###solusi sistem persamaan linier dengan matriks invers
###membuat soal sistem persamaan linier 6 variabel

##Pengertian Matriks Invers
Invers matriks adalah operasi matematika yang dilakukan terhadap sebuah matriks dengan tujuan untuk mendapatkan matriks yang jika dikalikan dengan matriks asalnya akan menghasilkan matriks identitas. Dalam istilah sederhana, invers matriks adalah kebalikan dari matriks tersebut.

Untuk matriks persegi \( A \) berukuran \( n \times n \), jika terdapat sebuah matriks \( B \) berukuran yang sama sehingga \( AB = BA = I \), di mana \( I \) adalah matriks identitas \( n \times n \), maka \( B \) adalah invers dari \( A \). Dinyatakan sebagai \( B = A^{-1} \).

Invers matriks hanya dapat ditemukan untuk matriks persegi yang memiliki determinan tidak sama dengan nol. Jika determinan matriks tersebut nol, maka matriks tersebut tidak memiliki invers.

Penerapan invers matriks sangat penting dalam berbagai bidang, termasuk sistem persamaan linear, analisis numerik, pemrosesan sinyal, grafika komputer, dan banyak lagi. Misalnya, dalam sistem persamaan linear, invers matriks digunakan untuk menemukan solusi unik dari sistem persamaan linear. Dalam pemrosesan sinyal, invers matriks digunakan dalam proses dekonvolusi untuk memulihkan sinyal asli dari sinyal yang telah dikonvolusi dengan fungsi tertentu.

##sifat sifat matriks
Tentu, berikut ini adalah penjelasan lebih lengkap tentang sifat-sifat invers matriks:

1. **Unik**: Setiap matriks persegi yang memiliki invers, memiliki invers yang unik. Ini berarti bahwa jika sebuah matriks \( A \) memiliki invers \( A^{-1} \), maka invers tersebut adalah satu-satunya matriks yang, jika dikalikan dengan \( A \), akan menghasilkan matriks identitas. Ini merupakan konsekuensi dari definisi invers matriks, di mana kita mencari matriks yang ketika dikalikan dengan matriks asalnya akan menghasilkan matriks identitas.

2. **Komutatif**: Invers matriks bersifat komutatif dalam hal perkalian. Artinya, jika sebuah matriks \( A \) memiliki invers \( A^{-1} \), maka invers dari invers tersebut \( (A^{-1})^{-1} \) adalah matriks \( A \) itu sendiri. Dalam istilah lain, jika kita menginverskan sebuah matriks yang sudah diinvers, kita akan mendapatkan kembali matriks asalnya. Hal ini dapat dibuktikan dengan melakukan perkalian antara \( A \) dan \( A^{-1} \), yang akan menghasilkan matriks identitas.

3. **Asosiatif**: Sifat asosiatif dalam konteks invers matriks berarti bahwa jika terdapat beberapa matriks yang dapat diinvers, maka perkalian antara matriks tersebut dengan inversnya dapat dilakukan dalam urutan apa pun. Artinya, jika \( A \), \( B \), dan \( C \) adalah matriks yang dapat diinvers, maka \( (AB)C = A(BC) \). Ini berarti kita dapat menggabungkan serangkaian perkalian matriks dan inversnya dalam urutan apa pun yang diinginkan tanpa mengubah hasil akhirnya.

4. **Perkalian dengan Identitas**: Salah satu sifat yang paling penting adalah bahwa jika suatu matriks \( A \) memiliki invers \( A^{-1} \), maka hasil perkalian antara \( A \) dengan inversnya \( A^{-1} \) adalah matriks identitas. Ini merupakan definisi utama dari invers matriks, yaitu untuk mendapatkan sebuah matriks yang ketika dikalikan dengan matriks asalnya akan menghasilkan matriks identitas.

5. **Determinan**: Determinan dari matriks invers \( A^{-1} \) adalah invers dari determinan matriks \( A \). Jika determinan matriks \( A \) tidak sama dengan nol, maka inversnya ada dan determinan inversnya dapat dihitung sebagai invers dari determinan matriks \( A \). Ini memberikan informasi penting tentang keberadaan invers matriks dan apakah invers tersebut dapat dihitung.

6. **Transpose**: Sifat transpose invers matriks menyatakan bahwa transpose dari invers matriks \( A^{-1} \) adalah invers dari transpose matriks \( A^T \). Dalam istilah lain, jika kita menginverskan matriks transpose, maka hasilnya adalah transpose dari invers matriks aslinya.

7. **Invers dari Penjumlahan dan Pengurangan**: Sifat ini mengatakan bahwa invers dari penjumlahan atau pengurangan dua matriks adalah penjumlahan atau pengurangan invers masing-masing matriks. Ini berarti jika \( A \) dan \( B \) adalah dua matriks yang dapat diinvers, maka \( (A + B)^{-1} = A^{-1} + B^{-1} \) dan \( (A - B)^{-1} = A^{-1} - B^{-1} \).

8. **Invers dari Skalar Kali Matriks**: Sifat ini menyatakan bahwa invers dari hasil skalar kali antara matriks \( A \) dan skalar \( k \) adalah hasil pembagian invers matriks \( A \) dengan skalar \( k \). Dengan kata lain, \( (kA)^{-1} = \frac{1}{k}A^{-1} \).

##mencari invers dengan eliminasi gauss jordan
Metode eliminasi Gauss-Jordan adalah teknik yang digunakan untuk mencari invers dari sebuah matriks. Langkah-langkahnya mirip dengan metode eliminasi Gauss untuk menyelesaikan sistem persamaan linear, tetapi dengan beberapa perubahan agar mencari invers.

Berikut adalah langkah-langkah untuk mencari invers matriks \( A \) menggunakan metode eliminasi Gauss-Jordan:

1. Bentuk matriks tambahan: Gabungkan matriks identitas \( I \) dengan matriks \( A \), yaitu \( [A | I] \). Matriks identitas adalah matriks persegi dengan elemen diagonalnya bernilai 1 dan elemen lainnya bernilai 0.

2. Terapkan eliminasi Gauss: Ubah matriks \( [A | I] \) menjadi bentuk baris eselon tereduksi. Ini dilakukan dengan mengubah setiap baris menjadi bentuk baris eselon melalui operasi baris dasar, seperti pengurangan dan pembagian baris. Tujuan dari langkah ini adalah untuk membawa matriks \( A \) ke dalam bentuk matriks identitas, sedangkan matriks \( I \) akan berubah menjadi invers dari matriks \( A \).

3. Kembali substitusi ke belakang: Setelah mendapatkan bentuk baris eselon tereduksi, aplikasikan eliminasi kembali ke belakang untuk mendapatkan bentuk invers matriks \( A \).

4. Hasilnya akan berupa \( [I | A^{-1}] \), di mana \( A^{-1} \) adalah invers dari matriks \( A \).

Mari kita ilustrasikan langkah-langkah ini dengan contoh:

Misalkan kita punya matriks \( A \):

\[ A = \begin{pmatrix} 2 & 1 \\ 1 & 3 \end{pmatrix} \]

Langkah-langkahnya adalah sebagai berikut:

1. Bentuk matriks tambahan:

\[ [A | I] = \begin{pmatrix} 2 & 1 & | & 1 & 0 \\ 1 & 3 & | & 0 & 1 \end{pmatrix} \]

2. Terapkan eliminasi Gauss:

\[ \begin{pmatrix} 2 & 1 & | & 1 & 0 \\ 1 & 3 & | & 0 & 1 \end{pmatrix} \rightarrow \begin{pmatrix} 1 & 0.5 & | & 0.5 & 0 \\ 0 & 2.5 & | & -0.5 & 1 \end{pmatrix} \]

3. Kembali substitusi ke belakang:

\[ \begin{pmatrix} 1 & 0 & | & 0.4 & -0.2 \\ 0 & 1 & | & -0.2 & 0.4 \end{pmatrix} \]

Maka invers dari matriks \( A \) adalah:

\[ A^{-1} = \begin{pmatrix} 0.4 & -0.2 \\ -0.2 & 0.4 \end{pmatrix} \]


In [6]:
import numpy as np
# Contoh penggunaan
A = np.array([[1, -1, 0],
              [1, 0, -1],
              [-6, 2, 3]])
A_inv = gauss_jordan_inverse(A)
print("Matriks A:\n", A)
print("Invers dari matriks A:\n", A_inv)

# Kalikan matriks invers dengan matriks A
result = np.dot(A_inv, A)
print("Hasil perkalian matriks invers dengan matriks A:\n", result)


Matriks A:
 [[ 1 -1  0]
 [ 1  0 -1]
 [-6  2  3]]
Invers dari matriks A:
 [[-2. -3. -1.]
 [-3. -3. -1.]
 [-2. -4. -1.]]
Hasil perkalian matriks invers dengan matriks A:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##solusi sistem persamaan linier dengan matriks invers
Berikut adalah contoh implementasi dalam Python untuk menyelesaikan sistem persamaan linier dengan menggunakan matriks invers:

In [2]:
import numpy as np

def solve_linear_system_with_inverse(A, b):
    A_inv = np.linalg.inv(A)
    x = np.dot(A_inv, b)
    return x

# Contoh penggunaan
A = np.array([[2, 1], [1, 3]])  # Matriks koefisien
b = np.array([5, 8])             # Vektor hasil

# Selesaikan sistem persamaan linier
solution = solve_linear_system_with_inverse(A, b)

print("Solusi x:")
print(solution)


Solusi x:
[1.4 2.2]


Outputnya akan menampilkan solusi x dari sistem persamaan linier. Kode ini dapat digunakan untuk menyelesaikan sistem persamaan linier yang lainnya dengan mengganti nilai A dan b sesuai dengan masalah yang diberikan. Pastikan bahwa matriks koefisien A memiliki invers agar metode ini dapat diterapkan.

##membuat soal sistem persamaan linier 6 variabel

Berikut adalah contoh soal sistem persamaan linier dengan 6 variabel beserta jawabannya:

**Soal:**
Tentukan solusi dari sistem persamaan linier berikut:

\[
\begin{cases}
2x + 3y - z + 4w - 5u + v = 10 \\
x - 2y + 3z - 4w + 5u - v = -5 \\
3x + 2y + z + w - 2u + 3v = 20 \\
-2x + y + z - 2w + u - 4v = -15 \\
4x - 3y + 2z + w + 3u - 2v = 25 \\
x + 4y - 3z - w + 2u - v = 10
\end{cases}
\]

**Jawaban:**
Untuk menyelesaikan sistem ini, kita dapat menggunakan matriks koefisien \( A \) dan vektor hasil \( b \), kemudian mencari invers dari \( A \) untuk mendapatkan solusi \( x \) dari sistem persamaan linier.

\[
A = \begin{bmatrix}
2 & 3 & -1 & 4 & -5 & 1 \\
1 & -2 & 3 & -4 & 5 & -1 \\
3 & 2 & 1 & 1 & -2 & 3 \\
-2 & 1 & 1 & -2 & 1 & -4 \\
4 & -3 & 2 & 1 & 3 & -2 \\
1 & 4 & -3 & -1 & 2 & -1 \\
\end{bmatrix}
\]

\[
b = \begin{bmatrix}
10 \\
-5 \\
20 \\
-15 \\
25 \\
10 \\
\end{bmatrix}
\]

Dengan menggunakan matriks invers, kita dapat menghitung solusi \( x \).

In [ ]:
import numpy as np
# Contoh penggunaan
B = np.array([[1, -1, 0],
              [1, 0, -1],
              [-6, 2, 3]]);
A_inv = gauss_jordan_inverse(A)
print("Matriks A:\n", A)
print("Invers dari matriks A:\n", A_inv)

# Kalikan matriks invers dengan matriks A
result = np.dot(A_inv, A)
print("Hasil perkalian matriks invers dengan matriks A:\n", result)
