## Aljabar Matrix
#  Tidak mengerjakan keluar kelas

- Berikan penjelasan tentang apa itu matrix

  *matriks adalah kumpulan bilangan atau elemen yang disusun dalam bentuk baris dan kolom. Setiap elemen dalam matriks diidentifikasi oleh baris dan kolomnya.
  matriks digunakan untuk merepresentasikan data, sistem linear, transformasi linear, dan berbagai konsep matematika lainnya.*

- jenis jenis matriks

  1. matriks nol : matriks yang seluruh elemennya adalah bilangan nol.
  2. matriks baris : matriks yang hanya memiliki satu baris.
  3. matriks kolom : matriks yang hanya memiliki satu kolom.
  4. matriks persegi : matriks yang banyaknya baris sama dengan banyaknya kolom.
  5. matriks diagonal : matriks persegi yang semua elemennya nol, kecuali pada diagonal utamanya.
  6. matriks segitiga atas, matriks persegi yang semua elemen di bawah diagonal utamanya adalah nol.
  7. matriks segitiga bawah : matriks persegi yang semua elemen di atas diagonal utamanya adalah nol.
  8. matriks identitas : matriks persegi yang elemen pada diagonal utamanya adalah satu, sedangkan elemen lainnya adalah nol.

- Operasi Matrix
  Operasi matriks dapat dilakukan hanya jika memenuhi syarat dan ketentuannya. Operasi matriks sendiri meliputi : penjumlahan dan pengurangan dua matriks, perkalian matriks dengan bilangan skalar, perkalian dua matriks, dan transpose matriks.

- penjumlahan dan pengurangan
  syarat : jika terdapat dua matriks, misal matriks j dan k, yang memiliki ordo sama, maka elemen yang seletak bisa dijumlahkan dan dikurangkan.

- Perkalian skalar
  pada operasi perkalian skalar, jika diketahui J merupakan suatu matriks dan K merupakan bilangan real, maka hasil perkalian K dengan matriks J adalah matriks yang diperoleh dengan mengalikan setiap elemen J dengan K.

- Perkalian dua matriks
  syarat perkalian dua matriks yaitu, kedua matriks memiliki jumlah kolom yang sama antara matriks A dengan Matriks B. untuk mencari hasil kali kedua matriks yitu dengan mengalikan elemen pada baris matriks A dengan elemen pada kolom matriks B, kemudian hasil perkalian antara baris dan kolom tersebut dijumlahkan.

- transpose matriks
  Transpose dari sebuah matriks adalah operasi untuk memindahkan elemen-elemen matriks ke posisi yang berlawanan secara diagonal. Artinya, jika sebuah matriks memiliki dimensi \( m \times n \), maka matriks transposenya akan memiliki dimensi \( n \times m \), dengan baris-baris dari matriks asli menjadi kolom-kolom dari matriks transposenya dan sebaliknya.

  Misalkan \( A \) adalah sebuah matriks dengan elemen \( a_{ij} \), di mana \( i \) menunjukkan indeks baris dan \( j \) menunjukkan indeks kolom. Transpose dari matriks \( A \), ditandai dengan \( A^T \), memiliki elemen yang sama, tetapi ditukar antara baris dan kolom, sehingga jika \( A^T \) adalah transpose dari \( A \), maka:

  \[ (A^T)_{ij} = a_{ji} \]


- buat program untuk mengalikan matriks a dan b tanpa menggunakan @


In [ ]:
import numpy as np

# Matriks A
A = np.array([[10, 7, 9],
              [9, 8, 10],
              [8, 9, 11]])
print("\nMatriks A :")
print(A)

# Matriks B
B = np.array([[1, 2, 3],
              [0, 3, 2],
              [-1, 4, 1]])
print("\nMatriks B :")
print(B)



Matriks A :
[[10  7  9]
 [ 9  8 10]
 [ 8  9 11]]

Matriks B :
[[ 1  2  3]
 [ 0  3  2]
 [-1  4  1]]


In [ ]:
#Penjumlahan

C = A + B
print("\nMatriks C :")
print(C)

D = B + C
print("\nMatriks D :")
print(D)

#Pengurangan

E = D - C
print("\nMatriks E : ")
print(E)

F = A - E
print("\nMatriks F :")
print(F)

#Transpose

A_T = A.transpose()
print('\nMatriks A Transpose')
print(A_T)

B_T = B.transpose()
print('\nMatriks B Transpose')
print(B_T)

C_T = C.transpose()
print('\nMatriks C Transpose')
print(C_T)

D_T = D.transpose()
print('\nMatriks D Transpose')
print(D_T)

E_T = A.transpose()
print('\nMatriks E Transpose')
print(E_T)

F_T = F.transpose()
print('\nMatriks F Transpose')
print(F_T)

#perkalian
G = A @ B
print ("\nMatriks G :")
print(G)

# Fungsi untuk mengalikan dua matriks
def multiply_matrices(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]
    return result


# Mengalikan dua matriks tanpa menggunakan @
result = multiply_matrices(A, B)

# Menampilkan hasil
print("\nHasil perkalian matriks A dan B:")
print(result)


Matriks C :
[[11  9 12]
 [ 9 11 12]
 [ 7 13 12]]

Matriks D :
[[12 11 15]
 [ 9 14 14]
 [ 6 17 13]]

Matriks E : 
[[ 1  2  3]
 [ 0  3  2]
 [-1  4  1]]

Matriks F :
[[ 9  5  6]
 [ 9  5  8]
 [ 9  5 10]]

Matriks A Transpose
[[10  9  8]
 [ 7  8  9]
 [ 9 10 11]]

Matriks B Transpose
[[ 1  0 -1]
 [ 2  3  4]
 [ 3  2  1]]

Matriks C Transpose
[[11  9  7]
 [ 9 11 13]
 [12 12 12]]

Matriks D Transpose
[[12  9  6]
 [11 14 17]
 [15 14 13]]

Matriks E Transpose
[[10  9  8]
 [ 7  8  9]
 [ 9 10 11]]

Matriks F Transpose
[[ 9  9  9]
 [ 5  5  5]
 [ 6  8 10]]

Matriks G :
[[ 1 77 53]
 [-1 82 53]
 [-3 87 53]]

Hasil perkalian matriks A dan B:
[[ 1. 77. 53.]
 [-1. 82. 53.]
 [-3. 87. 53.]]


In [ ]:
import numpy as np
import syampy as sy

buatlah matrix
a = 3x3
b = 3x3
c = 3x2

In [ ]:
import numpy as np
A = np.array([[2, 5, 9],[8, 4, 7], [9, 6, 2]]) #3x3
print("\nMatriks A")
print (A)
B = np.array([[10, -3, 0],[-5, -3, 2], [-1, -4, -9]]) #3x3
print("\nMatriks B")
print (B)
C = np.array ([[2, 1],[4, 1],[8, 0]]) #3x2
print("\nMatriks C")
print (C)
D = np.array ([[2, 1, 9],[4, 1, 10],[8, 0, 6]]) #3x3
print("\nMatriks D")
print (D)

# Menjumlahkan matriks A dan B
E = A + B

print("\nMatriks E")
print(E)

F = 2*A

print("\nMatriks F")
print(F)

G = A@C

print("\nMatriks G")
print(G)
print("\n")
print(G.shape)

H = B@C

print("\nMatriks H")
print(H)

#A(BC) = (AB) C
print ("\n A(BC) = (AB)C")
print((A@B) @C)

print ("\n A(BC) = (AB)C")
print(A@(B@C))

print ('\n A+B(C)')
print ((A+B)@C)
print('\n')
A_T = A.transpose()
print(A)
print('\n')
print(A_T)

C_T = C.transpose()
print('\nMatriks C Trans')
print(C_T)


Matriks A
[[2 5 9]
 [8 4 7]
 [9 6 2]]

Matriks B
[[10 -3  0]
 [-5 -3  2]
 [-1 -4 -9]]

Matriks C
[[2 1]
 [4 1]
 [8 0]]

Matriks D
[[ 2  1  9]
 [ 4  1 10]
 [ 8  0  6]]

Matriks E
[[12  2  9]
 [ 3  1  9]
 [ 8  2 -7]]

Matriks F
[[ 4 10 18]
 [16  8 14]
 [18 12  4]]

Matriks G
[[96  7]
 [88 12]
 [58 15]]


(3, 2)

Matriks H
[[  8   7]
 [ -6  -8]
 [-90  -5]]

 A(BC) = (AB)C
[[-824  -71]
 [-590  -11]
 [-144    5]]

 A(BC) = (AB)C
[[-824  -71]
 [-590  -11]
 [-144    5]]

 A+B(C)
[[104  14]
 [ 82   4]
 [-32  10]]


[[2 5 9]
 [8 4 7]
 [9 6 2]]


[[2 8 9]
 [5 4 6]
 [9 7 2]]

Matriks C Trans
[[2 4 8]
 [1 1 0]]
